FROM python:3.11
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt
EXPOSE 8000
COPY . /app
CMD uvicorn main:app --host 0.0.0.0 --port 8000 --reload