name: PDF Merger Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Build image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: jordanhennessy/pdf-merge-api
          tag: latest
          registry: docker.io
          username: ${{  }}
          password: ${{  }}
