name: PDF Merger Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: Build image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: jordanhennessy/pdf-merge-frontend
          directory: frontend
          tag: latest
          registry: docker.io
          dockerfile: Dockerfile-frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
